name: myworkflow
on: [push]
jobs:
  masterPacker:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies Including Ansible
        run: |
          python -m pip install ansible
          which ansible-playbook
          ansible-playbook --version
          PATH=$PATH:/opt/hostedtoolcache/Python/3.9.13/x64/bin/ansible-playbook
          echo $PATH

      - run: |
          ansible-playbook --version

  # we have to change the steps that use docker (hashicorp ones) and install things directly on github server 

      - name: Installs latest Packer
        uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: 1.7.0

      - name: validating master using packer
        run: |
          packer validate -syntax-only packer/master.pkr.hcl

      - name: build master using packer
        run: |
          packer build packer/master.pkr.hcl
  
  workerPacker:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies Including Ansible
        run: |
          python -m pip install ansible
          which ansible-playbook
          ansible-playbook --version
          PATH=$PATH:/opt/hostedtoolcache/Python/3.9.13/x64/bin/ansible-playbook
          echo $PATH

      - run: |
          ansible-playbook --version

  # we have to change the steps that use docker (hashicorp ones) and install things directly on github server 

      - name: Installs latest Packer
        uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: 1.7.0
      
      - name: validating worker using packer
        run: |
          packer validate -syntax-only packer/worker.pkr.hcl

      - name: build worker using packer
        run: |
          packer build packer/worker.pkr.hcl

  terraform:
    runs-on: ubuntu-latest
    needs: [masterPacker, workerPacker]
    steps:

      # group installing package steps together i.e. ansible, terraform etc
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.2

      - name: Terraform Init
        working-directory: ./terraform
        id: init
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        id: apply
        run: terraform apply -auto-approve

